### ISSUE TITLE
Decimals on speed ?

### ISSUE THREAD

**Issue by Valteur** [RuurdBijlsma/tm-split-speeds#5]
Hello.

I've wondering if it would possible to have a setting that shows decimals on speed.
Looking at the code, it would merely require to modify https://github.com/RuurdBijlsma/tm-split-speeds/blob/master/src/GUI.as#L32-L35 (and have it as a setting).

In developer mode, I could do that on my own without the setting, and I would just need to find how to transfer the already stored pb speeds.

> The speeds can vary by at most ~.5 km/h

What does this mean ? The speed gathering is inaccurate ? Is it true for all Trackmania games ? Even 2020 ?

Thank you
Sincerely,
Valteur

**Comment by RuurdBijlsma** [comment]
Yeah it's inaccurate, on a pf map you'll get different readings for the same checkpoint. Not because of tm btw, openplanet ticks don't run in sync with starting a run on a map, so checking the current speed at the openplanet tick you pass the checkpoint has some variation

So there's no point really in showing even 1 decimal, it'll be useless basically
